[package]
name = "nae-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"

linked_hash_set = "0.1.4"
#bigdecimal = "0.3.0"
rust_decimal = "1.23"
chrono = { version = "0.4.19", features = ["serde"] }
uuid = { version = "1.1.1", features = ["v4", "serde"] }

actix = "0.13"
actix-web = "4"
actix-web-actors = "4.1.0"

serde = { version = "1.0.137", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0.81"
#simd-json = "0.5.0"
#bincode = "1.3.3"

#ckb-rocksdb have transaction
rocksdb = { version = "0.18.0", default-features = false, features = ["lz4", "multi-threaded-cf"] }

blake2 = "0.10.4"

log = "0.4.17"
env_logger = "0.9.0"

[dev-dependencies]
tempfile = "3.3.0"