debug = false

[database]
memory = "./data/memory"
inventory = "./data/inventory"

[jwt_config]
audience = "https://yourdomain.com"
issuer = "Nae"
secret = "Rbv6xU9kwX8ViDsv8YxBuEAecxn7Z4PrRDaGjcN37YFnQJIHhdnHAlr9Mk4UBis"
